sonar.projectKey=scm-platform
sonar.projectName=SCM Platform
sonar.sourceEncoding=UTF-8
sonar.java.source=17
sonar.modules=scm-common,scm-common-spring,scm-oms-service,scm-wms-service,scm-tms-service,scm-erp-service
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=**/target/surefire-reports
